.PHONY: clean All

All:
	@echo "----------Building project:[ uocoworking - Debug ]----------"
	@cd "uocoworking" && "$(MAKE)" -f  "uocoworking.mk"
clean:
	@echo "----------Cleaning project:[ uocoworking - Debug ]----------"
	@cd "uocoworking" && "$(MAKE)" -f  "uocoworking.mk" clean
